### ISSUE TITLE
Preloading images corresponding to picture element

### ISSUE THREAD

**Issue by domfarolino** [w3c/preload#131]
This issue is a follow-up to the [HTML PR](https://github.com/whatwg/html/pull/4048) I made to support imagesrcset and imagesizes attributes on the `<link>` element. Some complications arose with the `<picture>` element use-case. In summary, I believe the first image source in a `<picture>` element whose `media` [matches the environment](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#matches-the-environment) is chosen to be loaded, and the rest are not loaded (until necessary). This contrasts with naturally independent `<link rel=preload>`s, in which all requests are mandatory.

If the author of a site is trying to preload images that a `<picture>` element may choose between, there will be `n - 1` wasted preloads for a given viewport. It seems that there are two solutions to this:

 - The author makes the `<link rel=preload>`s have mutually exclusive media queries, so that only one will be preloaded, the one that would be chosen in the `<picture>`. As noted, this might not always be feasible or easy for authors, and puts the burden on them.
 - The platform provides some sort of way to _explicitly_ link `<link rel=preload>`s together, so the UA knows that they ~correspond to a `<picture>`, and the same selection algorithm can be applied to choose the image to load. One [proposal](https://github.com/whatwg/html/pull/4048#issuecomment-425154049) was to create a new `rel` value to indicate this.

Thoughts? The latter seems to make sense, but I just want to make sure it is worth the complexity.

/cc @irori @zcorpan @developit

**Comment by toddreifsteck** [comment]
Discussed at TPAC 2018. Here is a summary based upon my interpretation of what was discussed:
* This adds a lot of complexity to preload's processing model
* There is not a clear, simple way to specify and implement
* This can be achieved almost as efficiently using a hidden picture element at the top of the body
* Because of this, we agreed to punt on investing further efforts until a real web site reports a need that cannot be worked around.
* Even when that need is reported, we believe it is likely to attempt to solve it by simpler modifications to preload than adding full picture capabilities.

**Comment by domfarolino** [comment]
Thanks for the summary, so to be clear, are we agreeing to abandon the HTML Standard PR supporting this?

**Comment by toddreifsteck** [comment]
@domfarolino Let me put a quick summary in #120

**Comment by yoavweiss** [comment]
Closing at this was the consensus in the group during the F2F. If and when we get reports that this is a missing capability which results in worse performance for production websites, we can reconsider.
