### ISSUE TITLE
Consider adding `type=module` for preload `as=script`

### ISSUE THREAD

**Issue by SMotaal** [w3c/preload#136]
Building off of the semi-adopted `<link rel=modulepreload …>`, is it time to consider the alternative `<link rel=preload as=script type=module …>` that aligns with other specified syntax for [`<link rel="preload" href="/assets/font.woff2" as="font" type="font/woff2">`](https://w3c.github.io/preload/#example-4-early-fetch-of-critical-resources).

It feels warranted to make this move to ensure starting to load the dependencies of a module graph early before new module loader extensions layer additional complications to such a specification (ie other proposals would best align with requirements for preload from the get go imho).

Somewhat relates to #116

**Comment by yoavweiss** [comment]
IIRC @domenic (who defined `modulepreload`) found the processing models for regular resources and modules to be different enough that a separate processing model was cleaner. I don't believe that has changed.

@domenic - do you have a link handy to your reasoning when making that call?

**Comment by domenic** [comment]
The spec itself contains the reasoning pretty clearly, I think: https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload

**Comment by domfarolino** [comment]
Is the argument for ‘as=script type=module’ (over ‘as=modulepreload’) purely syntactic? (I’m not sure I understand the second paragraph of OP’s comment).

**Comment by SMotaal** [comment]
I think it is all about perspectives… and from my point-of-view at least, the spec is detailing the developer-facing syntax and related object-level properties.

I would argue (from my POV) that the underlying implementation details are less prominent, and that the more visible issue for me was in trying to create a simple  `"preload"` abstraction layer and `"modulepreload"` sticking out on its own is complicating my efforts imho.

Worth mentioning also, from my best educated guess, implementations seem to actually be giving `"modulepreload"` a very different priority to say the least.

So as a developer, I'd like to have the full `"preload"` APIs or at least be able to use `import` or `script type="module"` and have it already preloaded… This would likely lead to gradual implementations which can be improved **by necessity** likely converging towards the `"modulepreload"` spec.

It is least reasonable to feel that `"modulepreload"` does not warrant that distinction from the developer's perspective… sounds fair?

**Comment by Media-Evil** [comment]
The [HTML spec](https://html.spec.whatwg.org/multipage/links.html#link-type-preload) says that value of `as` is a resource' [potential destination](https://fetch.spec.whatwg.org/#concept-request-destination), (for example, `script`, `worker`, `serviceworker` and `sharedworker`). What was the problem with standardizing a distinct destination for `module` scripts?

```
<link rel="preload" href="/module.mjs" as="module">.
```
Why this is bad?

**Comment by domenic** [comment]
Two reasons:

- then there's no way to tell if it's a module script, a module dedicated worker, a module shared worker, or a module service worker, because you used up the "destination" field which is meant for encoding the script/dedicated worker/shared worker/service worker distinction
- The destination field is not meant to dramatically change the processing model; it just gives the destination for the normal preload processing model. But the modulepreload processing module is very different from the preload processing model (as the spec explains, e.g. in security properties, module map usage, etc.). So destination is not an appropriate switch. Instead we should use a new rel, since that's how you indicate different processing models. (In other words, modulepreload is about as different from preload as stylesheet is.)

**Comment by Media-Evil** [comment]
I spent some time reflecting on this and so far I can say that I can only understand `classic` and `module` script destinations. When It comes to `worker`, `serviceworker` and `sharedworker` it isn't apparent to me why they even exist considering that web-worker's class and type [are defined declaratively](https://html.spec.whatwg.org/multipage/workers.html#module-worker-example):
```js
  const worker = new Worker("/module.mjs", { type: "module" });
```
Here the class depends on the used... class and type depends on the declared type, whereas
```
<link rel="preload" href="/module.mjs" as="module">.
```
aims to provide an early hint, allowing browsers to pre-process the resource in a meaningful way which for es-modules may/must? imply adding them to the module map, fetching dependencies, pre-compiling, etc. 

I would also argue that `destination` affects the processing model quite signifficantly: files loaded as `style`s affect the look of the page and are processed absolutely different than those loaded as `script`s (though both get preloaded).

Or I am missing something -__-?

**Comment by domenic** [comment]
The point of `as` (aka "destination") is to tell the browser how to prepare to use the file. It turns out the browser needs to do very different preparations for each destination: running as a `<script>`, running as a dedicated worker, running as a shared worker, or running as a service worker. If you say "prepare for running as a `script`", i.e. `rel="preload" as="script"`, and then do `new Worker("script.js")`, all those preparations will be wasted.

The same point holds in the parallel world of modules. If you say "prepare for running as a `<script type="module">`", i.e. `rel="modulepreload" as="script"`, then you cannot do `new Worker("script.mjs", { type: "module" })`.

In essence the browser needs 2 pieces of information (one with 2 choices, one with 4 choices) when it's being told to preload something. (Remember, at that time it has not seen any other code, such as your `new Worker()` code above.)

We've sliced this as `rel=preload|modulepreload` and `as=script|worker|sharedworker|serviceworker`, i.e. we've reified the 2x4 choices as a 2 options with 2 and 4 choices, respectively. You could imagine other approaches, e.g. using 8 different `as=""` values or even 8 different `rel=""`s. But since module vs. classic is orthogonal to `<script>` vs. dedicated worker vs. shared worker vs. service worker, the best approach is to use two `rel`s and four `as` values. This also works better because there's no precedent for different `as=""` values changing the meaning of other attributes (like `crossorigin=""`), but there is for different `rel=""` values.

**Comment by yoavweiss** [comment]
I believe this can be closed now, as the stand-alone preload spec is being discontinued. If you feel more discussion is needed, you can file an issue on HTML to continue it.
