### ISSUE TITLE
The `media` attribute and `<meta viewport>`

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#18]
There's some contention between defining resources to be loaded based on the `media` attribute (especially for preload, which must trigger as early as possible) inside `Link` headers, and the fact that developers that want to define mobile viewport dimensions have to do that using the `<meta viewport>` tag. Currently there's no way for developers to define viewport dimensions as an HTTP header.

I'm not sure what we can and should do about that, but it's worth while to try to address it. (or worst case, keep a note on it)

**Comment by igrigorik** [comment]
This is very similar to CSP+Link interaction (see https://github.com/w3c/resource-hints/issues/16, and [CSP complications section](https://w3c.github.io/webappsec/specs/CSP2/#complications)). Except, of course, that today we don't have a header-based mechanism to setting a viewport. 

In terms of moving forward on this:
1. I think we should allow use of media on `<link rel={preconnect, preload, prefetch, prerender} >` elements. This doesn't introduce any additional complications beyond existing requirements for setting the meta viewport early on. 
2. As a non-blocking issue, it may be worthwhile starting a conversation about enabling viewport declaration via an HTTP header? E.g. while its not an http-equiv, why couldn't we just map the `<meta>` into a `Viewport: width=device-width, initial-scale=1`?
   - For time being we would just add a "complications" section, similar to CSP, indicating that resources specified via `Link` header are not subject to media rules because there is no mechanism to declare the viewport via HTTP headers.

**Comment by igrigorik** [comment]
Hmm, actually, the current "[obtain the resource](http://www.w3.org/TR/html5/document-metadata.html#concept-link-obtain)" reference already provides `media` support for us. Do we have to do anything beyond this, short of providing test cases to make sure its implemented?

> However, if the link is an external resource link, then the media attribute is prescriptive. The user agent must apply the external resource when the media attribute's value matches the environment and the other relevant conditions apply, and must not apply it otherwise.

How do we interpret "apply" in the context of Preload and Resource Hints? 
- Resource Hints (preconnect, prefetch, prerender) are speculative, hence I'm inclined to say that "apply" in this context should mean that they're not triggered unless/until there is a matching MQ? That is, unless they're specified via `Link` response header, in which case they're always fetched.
- Preload has "must" semantics, but it doesn't have any "processing" beyond the fetch either. So, do we treat it the same way and defer until/unless there is a matching MQ? With same `Link` header stipulation as Resource Hints.

**Comment by igrigorik** [comment]
@yoavweiss @marcoscaceres @toddreifsteck any thoughts on this one?

**Comment by toddreifsteck** [comment]
After reading all referenced specs, my interpretation and thinking on how this would need to work matches Ilya's on media. I'll follow up with area experts internally on that and on viewport and share what I find.

**Comment by toddreifsteck** [comment]
Adding @jacobrossi

**Comment by jacobrossi** [comment]
Adding the media type into the preload args makes perfect sense.

As for letting meta viewport be an http-equiv.... I'd really rather not.  Meta viewport is a nasty thing.  Really nasty.  It has notorious interoperability issues given it originated as a Safari proprietary API that had undocumented "magic" behavior, some of which was based on iPhone/iPad devices specifically.  Browser implementations are largely a reverse engineering of that and Apple has tried adding more proprietary gunk to it, which results in further tail chasing. Because of this mess, browsers only support meta viewport on mobile devices (which is increasingly ambiguous in its definition).

The guidance we want to push is for sites to start using CSS Device Adaptation instead.  It has numerous improvements over meta viewport. For starters, it can be combined with media queries, which is amazingly powerful. But more importantly, it's being standardized and will work not just on mobile but all devices.

So IMO we shouldn't be expanding the capabilities of meta viewport.

**Comment by igrigorik** [comment]
@toddreifsteck @jacobrossi thanks guys. Putting viewport discussion aside, what's the behavior you'd expect for media queries on prefetch/preload/prerender? If we follow, say, CSS semantics, then the fetches are always triggered.. but since there is no "apply step", the whole thing becomes a no-op. So, should we only fetch resources when the MQ evaluates to true?

**Comment by toddreifsteck** [comment]
With regard to MQ, I agree that prefetch/preload/prerender should no-op if they don’t match the MQ.

Jacob, can you confirm your opinion?

**Comment by igrigorik** [comment]
@toddreifsteck just to confirm.. because when I said "no-op" I meant that if we allow MQ's but download regardless than MQ's are a no-op. Whereas, I think what you mean is that we should not download unless/until MQ evaluates to true -- correct?

**Comment by jacobrossi** [comment]
Yes I think that's what @toddreifsteck means. 

What if you want to preload a resource intended to be available should the state of the media change? 

Does preload/prefetch/prerender work for dynamically generated link elements?  If so, presumably a bit of script using a MQ list listener could make this work.

**Comment by jacobrossi** [comment]
Tagging in @gregwhitworth for his thoughts

**Comment by hexalys** [comment]
Full no-op could appear problematic to performance for the screen rotation context on mobile. You may want markup `link=preload`s' for landscape MQs already fetched as/before the user switch from portrait to landscape, or narrow snap mode to full width.

Could we perhaps leave browsers to speculate on such environment, so that conditional matching MQs may somehow be fetched early (but after page load) as `inert`, until such non-immediate MQ matches?

**Comment by yoavweiss** [comment]
Will answer in longer form when I'm next to a physical keyboard, but:
- CSS device adaptation is a performance anti pattern waiting to happen. We definitely should standardize viewport. I'm not convinced @viewport is the way to go (although recent agreements to limit it to the start of styles may make it more tolerable).
- long term, if we want preload in link headers to be sustainable, we need a way to define the viewport at this stage (other than data-URIying @viewport rules into link headers with a stylesheet rel)
- apply should mean download, and we shouldn't preload/prefetch when the Media doesn't apply. If a dev wants a resource to be ready for orientation change, they can define its media appropriately.

**Comment by hexalys** [comment]
> If a dev wants a resource to be ready for orientation change, they can define its media appropriately.

That's fine. The orientation change is workable.

However, could we defer the applicability of the rule **until** the environment matches, where the 'preload' _can still_ apply until `DOMContentLoaded`, if the viewport is resized dynamically before then. 

Use-cases:
1. Games, custom ideal viewport changes or specific fixed-width apps.
2. Desktop mode detection on mobile: What I do, is alter the `meta viewport` or `@viewport` dynamically when I detect a "desktop mode" condition, so I can present the user with a `desktop width` equivalent, instead of the default `device-width` responsive view. In this case the environment changes twice (from default-width to device-width to custom-width) before the page renders.

**Comment by yoavweiss** [comment]
Delaying preload kinda defeats is purpose. In these cases you can dynamically add the preload markup once you're certain the viewport is stable.

**Comment by hexalys** [comment]
True. However technically, in the desktop mode case, the large-screen/desktop rule would already be there in markup. So it requires scanning for existing preload rules using JS and re-add them exactly as they were. That seems very redundant.

**Comment by igrigorik** [comment]
> Does preload/prefetch/prerender work for dynamically generated link elements? If so, presumably a bit of script using a MQ list listener could make this work.

Yes. FWIW, all of the existing hints (e.g. prefetch, prerender) when injected via JS in Chrome.. Not sure about IE? The spec covers this behavior, see: http://w3c.github.io/preload/#fetching-the-preload-link

> apply should mean download, and we shouldn't preload/prefetch when the Media doesn't apply. If a dev wants a resource to be ready for orientation change, they can define its media appropriately.
> 
> Delaying preload kinda defeats is purpose. In these cases you can dynamically add the preload markup once you're certain the viewport is stable.

@yoavweiss I think the above two statements are at odds :)

FWIW, after thinking about this some more: 

Today MQ's control when the resource is applied, which is independent of the fetch: resources with matching MQ's are fetched immediately and with high priority; resources with non-matching MQ's are fetched with lower priority (e.g. in HTTP/1 the fetch may be delayed, in HTTP/2 we set a lower priority). As such, as far as fetching is concerned for existing elements, MQ's are a prioritization hint. 

In the context of preload... 
1. Not fetching until MQ matches is inconsistent with existing behavior of other elements, which -- I'm afraid -- may cause a lot of confusion and anti-patterns (e.g. fetch on orientation change -> jank). 
2. On the other hand, there is an argument here that there is no separate "apply" step for preload, and download == apply, hence defer the fetch. 

FWIW, personally I'm leaning towards (1) - i.e. continue to use MQs as prioritization hints. If you need to implement dynamic fetch behavior, then you can script it via JS. Also, this makes the whole Link+MQ's interop story not as painful.

Thoughts?

**Comment by yoavweiss** [comment]
> @yoavweiss I think the above two statements are at odds :)

Then let me clarify. By "viewport is stable" I meant that the appropriate `<meta name=viewport>` was applied and therefore the viewport will not change due to code changes (but may change due to env changes).

> Today MQ's control when the resource is applied, which is independent of the fetch: resources with matching MQ's are fetched immediately and with high priority; resources with non-matching MQ's are fetched with lower priority (e.g. in HTTP/1 the fetch may be delayed, in HTTP/2 we set a lower priority). As such, as far as fetching is concerned for existing elements, MQ's are a prioritization hint.

That's more of an historical accident with external stylesheet downloads then anything else. Attempts to change that behavior resulted in broken content and were reverted, so we're stuck with that behavior, but I don't think we should propagate it further.

> Not fetching until MQ matches is inconsistent with existing behavior of other elements, which -- I'm afraid -- may cause a lot of confusion

We're just talking about external stylesheets here, right? I would argue that the current behavior is the one causing confusion :)

> and anti-patterns (e.g. fetch on orientation change -> jank).

FWIW, for images, this is how we defined `<picture>`'s behavior with orientation changes. The developer can use CSS to make the transition invisible/prettier when appropriate. For other resources, that may not be ideal.

I think that (1) would render the `media` attribute on preload pretty useless.

OTOH, it may be a good idea to let the browser decide to "pre-preload" resources that may be needed after an orientation change, to shorten the time of orientation change transitions, and to reduce their "flashiness".

**Comment by hexalys** [comment]
As an author, MQs as generalized prioritization hints is definitely not my preference. While it may have browser legitimacy as failsafe, not to break content. It's at the expense of server resources, with the caveat of competing with maximum parallel downloads in HTTP1. The reduced performance implications and energy waste combined makes it an anti-pattern too.

If that legacy behavior has to stick around for backcompat. I would highly favor producing an option to opt out. What if we used the `pr` prioritization hint or some other flag (which could extend to stylesheets too) as an author's choice for how `preload` would treat MQs.  

e.g. `pr="0"` would strictly prohibit a `preload` fetch unless the MQ matches. Else, legacy behavior applies.

Leaving it up to the author in clear terms, is one long term approach to deal with that whole confusion.

**Comment by igrigorik** [comment]
> FWIW, for images, this is how we defined <picture>'s behavior with orientation changes. The developer can use CSS to make the transition invisible/prettier when appropriate. For other resources, that may not be ideal.

Ah, didn't think of `<picture>`.. good point. Do any of the current implementations do anything special for orientation or other types queries, or do they always defer the fetch until the MQ is matched? Also, can you point me to the language in `<picture>` that covers the fetch logic?

> As an author, MQs as generalized prioritization hints is definitely not my preference. While it may have browser legitimacy as failsafe, not to break content. It's at the expense of server resources, with the caveat of competing with maximum parallel downloads in HTTP1. The reduced performance implications and energy waste combined makes it an anti-pattern too.

@hexalys actually, as far as responsiveness and energy is concerned, you want to prefetch instead of delay-fetch. Unless we're strictly talking bytes shipped, leveraging an active radio channel yields better performance - see [more here](http://chimera.labs.oreilly.com/books/1230000000545/ch08.html#_burst_your_data_and_return_to_idle).

**Comment by hexalys** [comment]
@igrigorik Yes, I am aware of the radio channel benefits. But there is a trade-off for waste on the server side and more bytes than necessary, if not carefully minimized according to the _screen+device_ context. Hence my use of the term _generalized_.

For example: on a 534x824px Tablet with a `device-width` viewport definition. Unless we hit a use case like my 'desktop mode' example. Anything defined outside of those breakpoints, shouldn't download. Or say on desktop, do we really want to needlessly preload mobile breakpoints for a 1200+ browser width? Unless the window is resized during a given session, only the full screen MQs are worth applying IMO.
And on mobile, if the screen orientation is locked, that narrows it down to 'apply _only_ when it matches'.

My point being that there is no clear cut case of 'apply' vs _not_, without first considering the environment.

**Comment by igrigorik** [comment]
> My point being that there is no clear cut case of 'apply' vs not, without first considering the environment.

Sure, and UA has the context. As such, I think you're suggesting the same behavior as @yoavweiss: define apply as download, but allow the UA some leeway in how and when these fetches are initiated. Correct? FWIW, I think this makes sense, I just want to make sure that we've covered all the cases.

**Comment by hexalys** [comment]
> I think you're suggesting the same behavior as @yoavweiss.

Correct. And probably reverse align those leeway conditions as limits to external stylesheets in regards to MQs, so as not to prolongate that existing behavior, as he mentioned, or restrain it as much as possible.

Another thing worth clarifying in the spec is: At which point does the browser consider the `viewport` set.

**Comment by yoavweiss** [comment]
> Ah, didn't think of <picture>.. good point. Do any of the current implementations do anything special for orientation or other types queries, or do they always defer the fetch until the MQ is matched?

AFAIK, both Blink and Gecko fetch only the first source with a matched MQ

> Also, can you point me to the language in <picture> that covers the fetch logic?

The spec covers which [source-set is picked](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-source-set) (<source> or <img>), and then a [single "selected source" is picked](https://html.spec.whatwg.org/multipage/embedded-content.html#select-an-image-source) from that source-set.

The spec then specifies [HTMLImageElement's resource loading](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element:await-a-stable-state-2).

So, the spec does not specify (nor forbid) speculative, ahead-of-time resource loading for orientation changes. I'd say that this is something that doesn't always make sense for images (outside of battery savings, assuming that BW is cheap, and/or the user is very likely to perform orientation changes), since the transition UX can be smoothed over by CSS/animations.

**Comment by igrigorik** [comment]
Ok, I'm proposing we add the following to [3.2](https://w3c.github.io/preload/#fetching-the-preload-link): 

> The user agent SHOULD NOT obtain the specified resource if the value of the `media` attribute contains a [valid media query list](http://drafts.csswg.org/mediaqueries/#mq-list) that evaluates to false.

Does that cover what we need?

**Comment by yoavweiss** [comment]
Maybe `The user agent SHOULD NOT obtain the specified resource if the value of the media attribute contains an invalid media query list or a valid media query list that evaluates to false.`?

**Comment by yoavweiss** [comment]
Also - should preload with media attributes listen to MQ changes and trigger downloads if the env change happens later on? Should in-flight fetches be aborted?

**Comment by igrigorik** [comment]
- wording: lgtm.
- env change: yes, I thought that was implicit. Are there are any cases where this is not the case?
- in-flight fetches: "no" and we should leave this up to the UA - e.g. in HTTP/1 "abort" is very expensive (must close the entire connection), in HTTP/2 we can do a RST_STREAM, but even there it's probably worth letting the resource finish.

**Comment by hexalys** [comment]
> env change: yes, I thought that was implicit.

Works for me. Worth specifying though. The spec wasn't apparently sufficiently clear on that.

Also, got an idea to try and resolve the "contention between defining resources to be loaded based on the media attribute inside Link headers":

> just map the <meta> into a Viewport: width=device-width, initial-scale=1?

An alternative to consider would be to spec MQ Level 4 to treat MQs directed via `Link Header` as 'device-width, initial-scale=1' by default. Not sure that's possible or fits well in terms of CSS spec. But MQs in link headers isn't mentioned anywhere on Media Queries Level 4 draft yet.

That would allow for the contention with the current mobile default viewports (980px or 1024px) to go away. It's there for backward compatibility reason anyway. On the long term, Responsive Design seems to indicate that `device-width, initial-scale=1` becomes appropriate as the default to observe in the absence of viewport definition.

Thoughts?

**Comment by igrigorik** [comment]
> An alternative to consider would be to spec MQ Level 4 to treat MQs directed via Link Header as 'device-width, initial-scale=1' by default. Not sure that's possible or fits well in terms of CSS spec. But MQs in link headers isn't mentioned anywhere on Media Queries Level 4 draft yet.

Interesting idea, but I'm not the right person to comment on that :) Have you run this by this the CSS wg? That said, in either case, I don't consider the `Link` discussion to be blocking: it's a known limitation that applies to more than just Preload. If and when that gets resolved, we can circle back and add the right wording and hooks in this spec.

**Comment by igrigorik** [comment]
Added media clause to the "appropriate times to obtain the resource" section: http://w3c.github.io/preload/#fetching-the-preload-link
