### ISSUE TITLE
why not enhance prefetch?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/preload#3]
Spent a few minutes today researching existing prefetch behaviors and comparing them to the preload document https://w3c.github.io/preload/

I also searched the mailing list but didn't find a condensed answer to the following question:
**Why are we adding preload rather than enhancing prefetch?**

IE implements prefetch/prerender/dns-prefetch links:
https://msdn.microsoft.com/en-us/library/ie/dn265039(v=vs.85).aspx

Mozilla implements prefetch link as well as Link header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ 

HTML Standard’s prefetch reference:
http://www.w3.org/TR/html5/links.html#link-type-prefetch

**Comment by igrigorik** [comment]
Preload has very different semantics and offers **new** functionality to the platform.

Existing rel=prefetch is a speculative hint that is used by the app to indicate resources that _may_ be needed for the next navigation. As a result, the UA is free to decide (a) whether it should fetch them at all, (b) if it does, it will fetch them with lowest possible priority to avoid contention with resources required by the current page, (c) it has no context for type of resource and hence its relative priority.

By contrast, rel=preload is a declarative fetch with "MUST" semantics. That is, the browser must initiate the fetch when it processes the rel=prefetch directive (in markup or injected via JS) and it must fetch the resource with appropriate priority as indicated by "as" attribute. Further, the download does not block the `load` event, and there is _no_ processing on the response -- e.g. I can fetch a CSS file without applying it on the document or cause CSSOM to block on this fetch.

---

All that said, `rel=preload` + `loadpolicy=next` **is** equivalent to rel=prefetch -- this behavior is defined as part of [resource hints spec](http://w3c.github.io/resource-hints/#next-load-and-processing-policy). Why that instead of `rel=prefetch`? 

Arguably we could just continue with `rel=prefetch`, but in practice due to lack of a spec, different browsers have implemented it with different behaviors: some support dynamic injection, others don't; some support Link headers, other's don't; some allow fetches to continue across navigations, other's don't... As a result, you have no idea what behavior you're going to get, and either you'd have to rely on UA detection to work around it, or, we can just "start over" with consistent implementation via `rel=preload` + `loadpolicy=next`... That's the pitch :-)

**Comment by toddreifsteck** [comment]
Per discussion on last call, rel=prefetch exists in the world. Can we use rel and avoid loadPolicy and achieve the same goal as preload/resource-hints?

**Comment by igrigorik** [comment]
@toddreifsteck I think we addressed why preload != prefetch (see my previous comment). For preload + loadpolicy case, let's continue the discussion in https://github.com/w3c/resource-hints/issues/26, since that's where it's defined -- assuming we resolve that in favor of using prefetch/prerender, then we can remove loadpolicy from this spec as well (which is mostly a no-op here anyway).

**Comment by toddreifsteck** [comment]
Sounds good!
