### ISSUE TITLE
what exactly constitutes a successful load or an error?

### ISSUE THREAD

**Issue by getify** [w3c/preload#6]
200 is a successful load, right? What if content.length == 0?

What about 204?

What if you preload a URL that then tries to upgrade (1xx) say to a websocket connection? Is that success or failure?

Does the browser automatically follow 3xx redirects? Is that a load event? is there a separate event to know that a redirect is being followed?

Are all 4xx and 5xx errors?

**Comment by igrigorik** [comment]
Same definition and processing steps as Fetch: https://fetch.spec.whatwg.org/#concept-network-error

**Comment by getify** [comment]
Sorry, but I'm not finding any information at all there about specifics. Are there any somewhere that I'm missing?

**Comment by igrigorik** [comment]
If you step through [Fetch processing steps](https://fetch.spec.whatwg.org/#http-fetch) (look for "network error") you'll see where it would resolve to onerror - e.g. blocked due to security, exceeded redirect count, etc. For more fine-grained control (e.g. 204), you can extract the response object once onload fires and switch on its properties - see [1] and https://github.com/w3c/preload/issues/14.

[1] http://blog.gospodarets.com/fetch_in_action/

**Comment by igrigorik** [comment]
(closing, feel free to reopen if there is more to address here)
