### ISSUE TITLE
Font examples should include a `type` attribute

### ISSUE THREAD

**Issue by ghost** [w3c/preload#60]
Hello,

I just want to double check if this is the correct syntax or not?

< link rel="preload" href="https://fonts.gstatic.com/s/roboto/v15/2UX7WLTfW3W8TclTUvlFyQ.woff" as="font" type="font/woff2" crossorigin >

w3c does not say about the type tag part.

Thanks

**Comment by igrigorik** [comment]
Yes, that should be correct. That said, as a separate note: fonts.gstatic.com URLs are _not_ guaranteed by the Google Fonts team, so you want to be careful about embedding them in your markup.

/cc @yoavweiss for type attribute sanity-check (what's the status in Blink?)

**Comment by yoavweiss** [comment]
`type` attribute is [supported](https://codereview.chromium.org/1737173003/) in M50.

**Comment by yoavweiss** [comment]
If I read the issue correctly, I think it is about the spec examples not containing `type`. `type` is not mandatory, but it is strongly recommended for not-universally-supported file formats, as otherwise, compat issues may result from non-supporting browsers adding preload support.

e.g. Let's say that Safari would add preload support before adding woff2 support. If you're preloading woff2 files without a `type` attribute, safari would download them, even though they are not necessary there.

That may cause Safari to become _slower_ as a result of its support of preload, which will inhibit the Safari team from turning on the feature.

So, reopening and renaming appropriately.

**Comment by ghost** [comment]
Thank you igrigorik and yoavweiss. Yes agree I think it would be a good idea to include it in the preload spec, better to have the extra info as it totally makes sense to add it and I have it running fine on a test website right now on Chrome version 50 and Canary version 51. Thanks for quick answers.
