### ISSUE TITLE
Tighter definition of "load was successful"

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#83]
As part of efforts to resolve #80, I started working on https://github.com/whatwg/fetch/pull/442, which led me to add related tests on https://github.com/w3c/web-platform-tests/pull/4505.

As part of those tests, I was relying on a 500 response to fail as an unsuccessful load, and trigger an error event for the preloaded resource. [According](https://github.com/w3c/web-platform-tests/pull/4505#discussion_r96625733) to @annevk, that's not how it's supposed to work and there are privacy implications to exposing status code for cross-origin resources.

I think we need to tighten the definition of "successful" and be explicit about whether a failing status code triggers the error event or the load one. (and fully understand and write down privacy implications of that, if any)

**Comment by igrigorik** [comment]
Shouldn't this tightened for `<link>` in general? I don't think preload is special in any way?

**Comment by yoavweiss** [comment]
Actually, looking at the general `<link>` "obtain a resource", it seems to be covered there:
 > Once the attempts to obtain the resource and its critical subresources are complete, the user agent must, if the loads were successful, queue a task to fire an event named load at thelink element, or, if the resource or one of its critical subresources failed to completely load for any reason (e.g. DNS error, HTTP 404 response, a connection being prematurely closed, unsupported Content-Type), queue a task to fire an event named error at the link element. Non-network errors in processing the resource or its subresources (e.g. CSS parse errors, PNG decoding errors) are not failures for the purposes of this paragraph.

@annevk - seems like we're already exposing e.g. 404s of cross-origin resources using e.g. `<link rel=stylesheet>`

@igrigorik - I think we need to either adopt a similar language here or link to HTML's definitions.

**Comment by annevk** [comment]
Hmm, I guess we do. There is some whatwg/html issue about all this. Maybe it's time to write tests and tackle it. Though even if we expose it for text/css resources, I'm not sure we should do it for all. (Since rel=stylesheet also fails if it's not text/css, so it's quite limited in possible attacks.)

**Comment by yoavweiss** [comment]
Seems like [script](http://jsbin.com/hoxicetolu/edit?html,console) is also exposing the error event in such a case, and images do the same.

**Comment by annevk** [comment]
Does the 500 page actually serve up a valid script or image? Though I think for script you may be correct that it leaks.

**Comment by yoavweiss** [comment]
I don't think it does, but I doubt many servers do that (which means that a
server error on cross-origin image fetches is leaking through the failure
to get dimensions & decode)

**Comment by annevk** [comment]
How would you distinguish a 404 from a 200 HTML page using `<img>`? I don't think you can.

**Comment by yoavweiss** [comment]
Correct me if I'm wrong, but since styles don't trigger an error on invalid styles (according to spec quoted above), can't we use styles to exfiltrate error status codes from *any* resource type?

Even if `<img>` can't give us that info (as it also triggers error on image decoding problems), that doesn't prevent anyone from crafting a malicious page using `<link rel=style>` and get a hold of that data, right?

**Comment by annevk** [comment]
Stylesheet requires text/css as far as I know. There might be a leak with `<object>` though. But it's not as simple as it looks. (And perhaps we should close that one too.)

**Comment by yoavweiss** [comment]
Chrome and WebKit [seem](http://jsbin.com/tunacozupi/edit?html,console ) to be accepting `text/plain` just fine. I'd be surprised if `text/html` is different.

**Comment by annevk** [comment]
That's a security bug of sorts then in those browsers. Not checking the MIME type can lead to exploits. I believe that is how they got at Yahoo! Mail at some point.

**Comment by yoavweiss** [comment]
I'm not sure it actually does something with the content, all I checked is that it fires the load event when it gets a 200 (with non CSS content) and fires error on a 500.

**Comment by yoavweiss** [comment]
Paging Dr. @mikewest for opinions

**Comment by yoavweiss** [comment]
This is blocked on opinions from security folks.

/cc @mikewest @hillbrad

**Comment by hillbrad** [comment]
It is my understanding that the onload/onerror HTTP status cross-origin side-channel is a well-established fact of the platform.

Certainly on Facebook we've long assumed that this is the case, have paid bounties for attacks that use this to leak private information and have framework level protections to avoid leaking if someone is in a particular audience, returning a 200 status with a "not found" page instead of a 404 for those not in the subset, since the difference in the status code is observable cross-origin.

I also think that this is _relied on_ by some systems.  A sophisticated example is trying to load (in browsers that can use script to observe the onload/onerror events but can't do XHR) a specific asset from a mobile carrier which will return a different status if the user has paid data available.  I'm sure there are many simpler uses that do cross-origin loads of resources without CORS headers and have fallback handlers for failure cases.

This is not to argue for keeping it, but it has been this way for a long time and fixing it will probably break a lot of things.

**Comment by yoavweiss** [comment]
@hillbrad - so IIUC, triggering onerror in response to error status codes will not create a new attack vector, as this is already exposed. 

If that's the case, I suggest we'd expose it on `<link rel=preload>` as well, in order to enable such error handling for preloaded resources.

**Comment by annevk** [comment]
I'm still not entirely convinced. E.g., `<script>` no longer exposes it if you use `X-Content-Type-Options: nosniff` (unless the 404 happens to be a script).

**Comment by yoavweiss** [comment]
I think this will be closed by https://github.com/w3c/preload/pull/91 once it lands. Currently the PR has its own "load was successful" section, but it might not need it.

**Comment by igrigorik** [comment]
#91 landed, closing.
