### ISSUE TITLE
Link element interface extensions

### ISSUE THREAD

**Issue by annevk** [w3c/preload#95]
This section should be removed or just become a pointer to the HTML Standard. Having duplicate sources of truth hurts.

**Comment by yoavweiss** [comment]
I agree that multiple sources of truth hurt developers, and hard to keep in-sync.

Comparing the relevant sections:
* The one in the preload spec claims that `as` defines the request's initiator, while the HTML one does not. I don't think the "initiator" part is needed, so would be happy to see it removed.
* OTOH, `as` is needed to set the request type, in order for it to set the right "Accept" headers. That's not included in the HTML section, but it should be (probably in the "obtain" processing model?).
* likewise, we need to add some prose on how `as` is used to set the request's priority.
* Otherwise, we should keep around the example in some form.

**Comment by yoavweiss** [comment]
Relevant changes to Fetch at https://github.com/whatwg/fetch/pull/582
