### ISSUE TITLE
Define the "Preload Cache"

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#97]
We need to define the preload cache, as currently it is not defined and different implementations are doing [observably different things](https://bugzilla.mozilla.org/show_bug.cgi?id=1222633#c38).

I think the best place to define such a cache is in Fetch, but as this spec would be its main consumer, thought we should a) discuss it b) track it on this side as well

**Comment by igrigorik** [comment]
Note: address discussion in #85 when we tackle this.

**Comment by addyosmani** [comment]
+1. My intuition is this belongs in Fetch and I'd be curious how closely we could get a preload cache matching HTTP cache semantics. The double download possibilities in some browsers would otherwise be unfortunate. 

Do we have a Fetch issue to cross-reference?

**Comment by yoavweiss** [comment]
Opened https://github.com/whatwg/fetch/issues/590 on Fetch. I'm not sure there's any immediate action on the preload spec, so closing this issue here. Let me know if you disagree.

**Comment by annevk** [comment]
I don't think you should close this until it's actually fixed on the Fetch side. This specification is the cause.

**Comment by yoavweiss** [comment]
Fair enough. Reopening

**Comment by toddreifsteck** [comment]
Discussed at TPAC 2018:
* The folks in the room agreed that downloads should, in principle, we predictable.
* Caches may be cleared by UAs due to memory pressure or to protect user privacy. Apple voices concerns that anything specificied may be difficult to observe in the real world.
* @yoavweiss will move forward on working to define how this behaves across UAs and in creating tests to poke at the diffrences across UAs.

**Comment by noamr** [comment]
See [HTML](https://github.com/whatwg/html/pull/7260) and [FETCH](https://github.com/whatwg/fetch/pull/1342) PRs

**Comment by noamr** [comment]
Closing as the preload cache is now defined. Feel free to reopen if I've missed something

**Comment by yoavweiss** [comment]
Yay!! \o/
